# API

runprod:
	ENV=production go run main.go

test:
	curl "http://localhost:8080/api/v1/matches?gameName=%E0%B9%80%E0%B8%9E%E0%B8%8A%E0%B8%A3&tagLine=ARAM" -I

test2:
	curl "http://localhost:8080/api/v1/matches?gameName=NOPEEEE&tagLine=nopeeeee" -I
