# API

runprod:
	ENV=production go run main.go

test:
	curl "http://localhost:8080/api/v1/matches?gameName=เพชร&tagLine=ARAM" -I

test2:
	curl "http://localhost:8080/api/v1/matches?gameName=เพชร&tagLine=ARAMnopeeeee" -I
