name: Test on Push (goapi)
on:
  push:
    paths:
      - "goapi/**"
      - "scripts/goapi-test/**"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  api-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: Run mockapi
        run: nohup go run cmd/mockapi/main.go > /dev/null & echo 'started mockapi'
        working-directory: goapi
      - name: Run goapi
        run: nohup go run cmd/goapi/main.go > /dev/null & echo 'started goapi'
        working-directory: goapi
      - name: Run script
        run: go run scripts/goapi-test/main.go
