name: Test on Push (go-api)
on:
  push:
    # paths:
      # - "go-api/**"

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: Run mock-api
        run: nohup go run cmd/mock-api/main.go > /dev/null & echo 'started mock-api'
        working-directory: go-api
      - name: Run go-api
        run: nohup go run cmd/go-api/main.go > /dev/null & echo 'started go-api'
        working-directory: go-api
      - name: Curl endpoint /api/health
        run: curl --retry 5 --retry-delay 2 --retry-connrefused http://localhost:8080/api/health -I
      - name: Curl endpoint /api/v1/matches
        run: curl http://localhost:8080/api/v1/matches?gameName=GAMENAME&tagLine=TAGLINE -I
